backend:
  name: git-gateway
publish_mode: editorial_workflow
media_folder: "assets/uploads"
collections:
  - name: "pages"
    label: "Page"
    folder: "src/site/pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "page" }
      - { label: "CreateRoute", name: "createRoute", widget: "hidden", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
